INSERT INTO category (description) VALUES ('Amerykanska');
INSERT INTO category (description) VALUES ('Meksykanska');
INSERT INTO category (description) VALUES ('Polska');
INSERT INTO category (description) VALUES ('Francuska');
INSERT INTO category (description) VALUES ('Fast Food');
INSERT INTO unit_of_measure (description) VALUES ('Lyzeczka');
INSERT INTO unit_of_measure (description) VALUES ('Lyzka');
INSERT INTO unit_of_measure (description) VALUES ('Szklanka');
INSERT INTO unit_of_measure (description) VALUES ('Szczypta');
INSERT INTO unit_of_measure (description) VALUES ('Uncja');
INSERT INTO unit_of_measure (description) VALUES ('Kazdy');
INSERT INTO unit_of_measure (description) VALUES ('Pinta');